config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  post 'isbn', to:'books#isbn'
  resources :books, only: [:show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :my_books
      get :my_posts
      get :likes
    end
  end
  
  resources :posts, except: [:show]
  
  post 'read', to: 'shelves#read'
  resources :shelves, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  has_many :books
  
  has_many :shelves, class_name: 'Shelf', foreign_key: 'user_id'
  has_many :my_books, through: :shelves, source: :book
  
  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :post

  
  def have(book)
    self.shelves.find_or_create_by(book_id: book.id)
  end
  
  def unhave(book)
    shelf = self.shelves.find_by(book_id: book.id)
    shelf.destroy if shelf
  end
  
  def having?(book)
    self.my_books.include?(book)
  end
  
  def posted(book)
    shelf = self.shelves.find_by(book_id: book.id)
    shelf.post_flag = 'true'
    shelf.save
  end
  
  def unpost(post)
    shelf = self.shelves.find_by(book_id: post.book_id)
    shelf.post_flag = 'false'
    shelf.save
  end
  
  def read(book)
    shelf = self.shelves.find_by(book_id: book.id)
    shelf.read_flag = 'true'
    shelf.save
  end
  
  def like(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def like?(post)
    self.likes.include?(post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def my_books
    @user = User.find(params[:id])
    @my_books = @user.my_books.page(params[:page])
    counts(@user)
  end
  
  def  my_posts
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_read_button.html.erb
<%= form_with(url: read_path, local: true) do |f| %>
  <% @shelf = current_user.shelves.find_by(book_id: my_book.id) %>
  <%= hidden_field_tag :book_id, @shelf.book_id %>
  <% if @shelf.read_flag %> 
    <p><%= '既読' %></p>
  <% else %>
    <%= f.submit '未読', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<% if @users.any? %>
  <% @users.each do |user| %>
    <ul class="list-unstyled">
      <li class="media mb-3">
        <img class="mr-3 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
          <div class="media-body">
            <% if current_user == user %>
              <p><%= link_to user.name, my_books_user_path(user) %></p>
            <% else %>
              <p><%= link_to user.name, user_path(user) %></p>
            <% end %>
            <div class="row">
              <div class="mr-3">
              <p>レビュー投稿数：<%= user.posts.count %></p>
              </div>
              <div>
               <p>読み終わった本：<%= user.shelves.where(read_flag: 'true').count %>冊</p>
              </div>
            </div>
          </div>
      </li>
    </ul>
  <% end %>
  <%= paginate @users %>
<% end %>

app/views/users/my_books.html.erb
<% if current_user == @user %>
  <div class="row">
    <aside class="col-sm-2">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 200 }) %>" alt="">
      <h3><%= @user.name %></h3>
      <p>レビュー投稿数：<%= @count_posts %></p>
      <p>読み終わった本：<%= @count_read %>冊</p>
    </aside>
    <div class="col-sm-10">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= my_books_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(my_books_user_path(@user)) %>">本棚</a></li>
        <li class="nav-item"><a href="<%= my_posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(my_posts_user_path(@user)) %>">投稿</a></li>
      </ul>
      <ul class="list-unstyled">
        <% @my_books.each do |my_book| %>
          <li class="mb-3">
            <div class="container">
              <div class="row">
                <div class="col-5"><%= my_book.title %></div>
                <div class="col-3"><%= my_book.author %></div>
                <div class="col-2"><%= render 'posts/post_button', my_book: my_book %></div>
                <div class="col-2"><%= render 'read_button', my_book: my_book %></div>
              </div>
            </div>
          </li>
        <% end %>
        <%= paginate @my_books %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/my_posts.html.erb
<div class="row">
  <aside class="col-sm-2">
    <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 200 }) %>" alt="">
    <h3><%= @user.name %></h3>
    <p>レビュー投稿数：<%= @count_posts %></p>
    <p>読み終わった本：<%= @count_read %>冊</p>
  </aside>
  <div class="col-sm-10">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= my_books_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(my_books_user_path(@user)) %>">本棚</a></li>
      <li class="nav-item"><a href="<%= my_posts_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(my_posts_user_path(@user)) %>">投稿</a></li>
    </ul>
    <% if @posts.any? %>
      <ul class="list-unstyled">
        <% @posts.each do |post| %>
          <% post_book = Book.find(post.book_id) %>
          <div class="row">
            <div class="ml-2 mr-3">
              <p><%= post_book.title %></p>
            </div>
            <div class="mr-3">
              <p><%= post_book.author %></p>
            </div>
            <div class="ml-2 mr-3">
              <p>いいねをもらった数：<%= post.likes.count %></p>
            </div>
          </div>
          <div class="row ml-2 mb-3">
            <div class="col-10">
              <p><%= post.content %></p>
           </div>
            <div class="col-2">
              <div class="row">
                <div class="mr-1">
                  <%= render 'posts/post_edit_button', post: post %>
                </div>
                <%= render 'posts/post_delete_button', post: post %>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @posts %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Reading</h1>
  <h2>ユーザ登録</h2>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ニックネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, '確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-success btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-2">
    <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 200 }) %>" alt="">
    <h3><%= @user.name %></h3>
    <p>レビュー投稿数：<%= @count_posts %></p>
    <p>読み終わった本：<%= @count_read %>冊</p>
  </aside>
  <div class="col-sm-10">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item">投稿</li>
    </ul>
    <% if @posts.any? %>
      <ul class="list-unstyled">
        <% @posts.each do |post| %>
          <% post_book = Book.find(post.book_id) %>
          <div class="row">
            <div class="mr-3">
              <p><%= post_book.title %></p>
            </div>
            <div class="mr-3">
              <p><%= post_book.author %></p>
            </div>
            <div>
              <p>いいねをもらった数：<%= post.likes.count %></p>
            </div>
          </div>
          <div class="mb-3">
            <p><%= post.content %></p>
          </div>
          <div class="mb-3">
            <%= render 'favorites/favorite_button', post: post %>
          </div>
        <% end %>
        <%= paginate @posts %>
      </ul>
    <% end %>
  </div>
</div>