config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  post 'isbn', to:'books#isbn'
  resources :books, only: [:show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :my_books
      get :my_posts
      get :likes
    end
  end
  
  resources :posts, except: [:show]
  
  post 'read', to: 'shelves#read'
  resources :shelves, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    if params[:keyword]
      @books = RakutenWebService::Books::Book.search(title: params[:keyword])
    end
  end

end

app/views/toppages/_book_list.html.erb
<% if books.present? %>
  <% if @books.count == 0 %>
    <%= '検索を実行しましたが、お探しの書籍は見当たりませんでした。' %>
  <% else %>
    <p>検索結果<%= @books.count %>件(最大３０件までを表示)</p>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>著者</th>
          <th>価格</th>
          <th></th>
        </tr>
      </thead>
      <% books.each do |book| %>
          <tbody>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td>¥<%= book.item_price %></td>
              <td><%= link_to '選択', isbn_path(isbn: book.isbn), method: :post, class: 'btn btn-success btn-sm' %></td>
            </tr>
          </tbody>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<h1>Reading</h1>

<h4>本を検索する</h4><br>
<b>必ず本のタイトルまたは、本のタイトルのキーワードを入力してください。複数検索の場合もタイトルのキーワードで検索してください。</b><br>
<b>(作者、サブタイトル等を入力しても検索結果が表示されない場合があります。）</b><br>
<b><font color="red">※楽天ブックスの本（紙の書籍）のみが対象となります。電子書籍、雑誌、洋書、DVD、CD、音楽配信、ゲーム、PCソフト等は対象外となります。</font></b><br><br>
<%= form_with(url: root_path, method: :get, local: true) do |f| %>
  <div class="form-group input-group">
    <%= f.text_field :keyword, class: 'form-control', required: true, minlength: 2, maxlength: 60, placeholder: '例：吾輩は猫である、吾輩'%>
    <div class="input-group-append">
      <%= f.submit '検索', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>
<%= render 'toppages/book_list', books: @books %>