config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  post 'isbn', to:'books#isbn'
  resources :books, only: [:show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :my_books
      get :my_posts
      get :likes
    end
  end
  
  resources :posts, except: [:show]
  
  post 'read', to: 'shelves#read'
  resources :shelves, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  has_many :favorites, dependent: :destroy
  has_many :likes,  through: :favorites, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in

  def index
    @posts = Posts.find_by(book_id: params[:book_id])
  end
  
  def new
    @post = current_user.posts.build
    @book = Book.find(params[:book_id])
  end
  
  def create
    @post = current_user.posts.build(post_params)
    @post.book_id = params[:book_id]
    @book = Book.find(params[:book_id])
    if @post.save
      current_user.posted(@book)
      flash[:success] = 'レビューを投稿しました。'
      redirect_to my_posts_user_path(current_user)
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'レビューの投稿に失敗しました。'
      render :new
    end
  end
  
  def edit
    @post = current_user.posts.find(params[:post_id])
    params[:book_id] = @post.book_id
    @book = Book.find(params[:book_id])
  end
  
  def update
    @post = current_user.posts.find(params[:post_id])
    params[:book_id] = @post.book_id
    @book = Book.find(params[:book_id])
    if @post.update(post_params)
      current_user.posted(@book)
      flash[:success] = 'レビューを投稿しました。'
      redirect_to my_posts_user_path(current_user)
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'レビューの投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:post_id])
    current_user.unpost(@post)
    @post.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def post_params
    params.require(:post).permit(:content)
  end
  
end

app/views/posts/_post_button.html.erb
<%= form_with(url: new_post_path, local: true, method: :get) do |f| %>
  <% @shelf = current_user.shelves.find_by(book_id: my_book.id) %>
  <%= hidden_field_tag :book_id, @shelf.book_id %>
  <% if @shelf.post_flag %> 
    <p><%= '投稿済' %></p>
  <% else %>
    <%= f.submit '投稿', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% end %>

app/views/posts/_post_delete_button.html.erb
<%= form_with(url: post_path, local: true, method: :delete) do |f| %>
  <%= hidden_field_tag :post_id, post.id %>
  <%= f.submit '削除', data: { confirm: "You sure?" },  class: 'btn btn-danger btn-sm' %>
<% end %>

app/views/posts/_post_edit_button.html.erb
<%= form_with(url: edit_post_path, local: true, method: :get) do |f| %>
  <%= hidden_field_tag :post_id, post.id %>
  <%= f.submit '編集', class: 'btn btn-success btn-sm' %>
<% end %>

app/views/posts/edit.html.erb
<ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= edit_post_path(current_user) %>" class="nav-link active">投稿編集</a></li>
  <li class="nav-item"><a href="<%= my_books_user_path(current_user) %>" class="nav-link" >本棚</a></li>
  <li class="nav-item"><a href="<%= my_posts_user_path(current_user) %>" class="nav-link">投稿</a></li>
</ul> 
<div class="row">
  <div class="ml-3 mr-3">
    <p><%= @book.title %></p>
  </div>
  <div>
    <p><%= @book.author %></p>
  </div>
</div>
<%= form_with(model: @post, local: true, method: :patch) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', rows: 20 %>
    <%= hidden_field_tag :post_id, @post.id %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-success btn-block'%>
<% end %>

app/views/posts/new.html.erb
<ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= new_post_path(current_user) %>" class="nav-link active">新規投稿</a></li>
  <li class="nav-item"><a href="<%= my_books_user_path(current_user) %>" class="nav-link" >本棚</a></li>
  <li class="nav-item"><a href="<%= my_posts_user_path(current_user) %>" class="nav-link">投稿</a></li>
</ul> 
<div class="row">
  <div class="ml-3 mr-3">
    <p><%= @book.title %></p>
  </div>
  <div>
    <p><%= @book.author %></p>
  </div>
</div>
<%= form_with(model: @post, local: true, method: :post) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', rows: 20 %>
    <%= hidden_field_tag :book_id, params[:book_id] %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-success btn-block' %>
<% end %>